### ISSUE TITLE
dependency version for sieverules wrong?

### ISSUE THREAD

**Issue by user7466** [JohnDoh/Roundcube-Plugin-QuickRules#7]
I have roundcube 1.0.5, with sieverules dev-release-2.0 already installed.
I am trying to install quickrules dev-release-2.0, but it has a dependency on "johndoh/sieverules: >=2.0"

composer only thinks sieverules dev-master meets this dependency.

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Can only install one of: johndoh/sieverules[dev-master, dev-release-2.0].
    - Can only install one of: johndoh/sieverules[dev-release-2.0, dev-master].
    - johndoh/quickrules dev-release-2.0 requires johndoh/sieverules >=2.0 -> satisfiable by johndoh/sieverules[dev-master].
    - Installation request for johndoh/quickrules dev-release-2.0 -> satisfiable by johndoh/quickrules[dev-release-2.0].
    - Installation request for johndoh/sieverules dev-release-2.0 -> satisfiable by johndoh/sieverules[dev-release-2.0].
```
Should the dependency not be on "johndoh/sieverules: >=dev-release-2.0"?

cheers....

**Comment by JohnDoh** [comment]
Yes there are problems there. I know very little about composer. I have asked others but no one can explain why plugins.roundcube.net refuses to pick up the tags from github.

Version 2.2 of SieveRules (for Roundcube 1.1) has the QuickRules functionality built into it so when 1.1 is released this plugin will be scrapped and then this problem will be gone.
